trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: sourceProject
  type: string
  default: "ONE!"'
- name: sourceArea
  type: string
  default: 'ONE!\\xx_Sandkasten'
- name: destinationProject
  type: string
  default: 'ONE! Program_Dev'
- name: destinationArea
  type: string
  default: 'ONE! Program_Dev'
- name: PAT
  type: string
  default: 'hy5ljfnuzezpn5ojdasxtlhrfgopbpt3ezgrmaq5fqzsd7z4yfsa'
- name: sourceProjectID
  type: string
  default: '38def788-c6c3-414b-b0e3-b017687f4701'
- name: targetProjectID
  type: string
  default: 'f7db8333-e29d-4dc4-8c52-cb0249449af2'
  
variables:
  - group: Security

steps:
- checkout: self
  displayName: 'Checkout Code'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'DynamicLinkedWorkitemCloning.ps1'
    arguments: '-SourceProject "${{ parameters.sourceProject }}" -SourceArea "${{ parameters.sourceArea }}" -DestinationProject "${{ parameters.destinationProject }}" -DestinationArea "${{ parameters.destinationArea }}" -PAT "${{ parameters.PAT }}"'
    pwsh: true
  displayName: 'Run Azure DevOps PowerShell Script'

