trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: sourceProject
  type: string
  default: 'DefaultSourceProject'
- name: sourceArea
  type: string
  default: 'DefaultSourceArea'
- name: destinationProject
  type: string
  default: 'DefaultDestinationProject'
- name: destinationArea
  type: string
  default: 'DefaultDestinationArea'
- name: PAT
  type: string
  default: 'DefaultPAT'

variables:
  - group: Security

steps:
- checkout: self
  displayName: 'Checkout Code'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'DynamicLinkedWorkitemCloning.ps1'
    arguments: '-SourceProject "${{ parameters.sourceProject }}" -SourceArea "${{ parameters.sourceArea }}" -DestinationProject "${{ parameters.destinationProject }}" -DestinationArea "${{ parameters.destinationArea }}" -PAT "${{ parameters.PAT }}"'
    pwsh: true
  displayName: 'Run Azure DevOps PowerShell Script'

