   trigger:
     branches:
       include:
       - main  # Trigger on changes to the main branch

   pool:
     vmImage: 'ubuntu-latest'

   steps:
   - checkout: self
   - script: |
       git config --global user.email "you@example.com"
       git config --global user.name "Your Name"
       git remote add github https://github.com/USERNAME/REPOSITORY.git
       git push github HEAD:main --force  # Adjust the branch names as necessary
     env:
       GITHUB_TOKEN: $(GitHubToken)  # Use the secret variable
     displayName: 'Push changes to GitHub'